### ISSUE TITLE
Can not add the binary repository for rabbitmq on Ubuntu 20.04.1 LTS 

### ISSUE THREAD

**Issue by skalenji** [mediafellows/ansible-role-rabbitmq#1]
The role fails on Ubuntu 20.04.1 LTS with "msg: apt cache update failed"

This happens when executing the `Add RabbitMQ apt repo` task in `/tasks/install_rabbit.yml`.

The issue seems to be this line:
`repo: "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main"`
On Ubuntu Focal this will resolve to `https://dl.bintray.com/rabbitmq/debian focal Release`, however such repository does not exist.
This can be tested directly with apt:
`add-apt-repository deb https://dl.bintray.com/rabbitmq/debian focal main` 
returns:
`Err:9 https://dl.bintray.com/rabbitmq/debian focal Release
  404  Not Found `
`E: The repository 'https://dl.bintray.com/rabbitmq/debian focal Release' does not have a Release file.`

According to the rabbitmq documentation "bionic" should be used as distribution name it should work for any later Ubuntu or Debian release.

It seems that in this case using `{{ ansible_distribution_release }}` actually makes the role incompatible with newer releases and hardcoded value ("bionic") will be more appropriate. 
This however will break compatibility with older distributions. Maybe a better approach will be to make this task conditional for older releases then have another one without the `{{ ansible_distribution_release }} ` which is also conditional for newer releases.

I can make a fork with the fix but I am unable to test it on all supported distros

**Comment by stefanhorning** [comment]
Thanks for your report. Somehow didn't notice your comment so far. Will try to look into this. I believe s.b. already opened a PR for this here https://github.com/mediafellows/ansible-role-rabbitmq/pull/3

**Comment by stefanhorning** [comment]
This should be now fixed with the merge of #3
